Repository DoobDev/Doob, pull requests merged in 2020-09, with the labels that each got.

#33 Update README.md
  README.md
Labels: size/XS

#32 Update README.md rewrite
  README.md
Labels: size/M

#45 Update README.md
  README.md
Labels: size/XS

#49 e
  README.md
Labels: merge when green, size/XS

#63 README corrections.
  README.md
Labels: size/S

#64 Update greetings.yml
  .github/workflows/greetings.yml
Labels: size/XS
