Repository DoobDev/Doob, pull requests merged in 2020-11, with the labels that each got.

#85 merge (bitch)
  lib/cogs/fun.py
Labels: size/S

#88 Made the mute required permissions normal, Matt.
  lib/cogs/mod.py
Labels: size/XS

#97 [WIP] Game Stats
  CHANGELOG.md
  data/db/build.sql
  lib/cogs/gamestats.py
Labels: Medium Priority, enhancement, feature_request, size/L

#98 change titles
  lib/cogs/twitch.py
Labels: merge when green

#94 [WIP] Adding Comments
  data/db/build.sql
  lib/bot/__init__.py
  lib/cogs/fun.py
Labels: development, size/M

#99 Bio command
  lib/cogs/bio.py
  requirements.txt
Labels: High Priority, feature_request, size/M

#100 Last.fm command
  .env_example
  data/db/build.sql
  lib/NOT IN USE/servercount.py
  lib/NOT IN USE/stat.py
  lib/cogs/lastfm.py
Labels: High Priority, feature_request

#101 Last.fm subcommands
  CHANGELOG.md
  lib/cogs/lastfm.py
  lib/cogs/meta.py
Labels: High Priority, feature_request, size/M

#102 Actually finishing comments
  lib/cogs/bio.py
  lib/cogs/fun.py
  lib/cogs/gamestats.py
Labels: development, size/M
