Repository DoobDev/Doob, pull requests merged in 2021-03, with the labels that each got.

#151 ➕Add Emojis to `README.md`
  README.md
Labels: size/S

#152 ➕Added `owoify` command
  CHANGELOG.md
  launcher.py
  lib/cogs/fun.py
  requirements.txt
Labels: size/S

#158 ➕Added `GitHub` commands.
  .env_example
  CHANGELOG.md
  launcher.py
  lib/cogs/github.py
  requirements.txt
Labels: size/L

#159 🔀Changed the style of `README.md`
  README.md
Labels: size/M

#166 ➕Added priority labels to `d!issue -c`
  CHANGELOG.md
  lib/cogs/github.py
Labels: size/S

#150 ➕Added `DogeHouse` commands
  CHANGELOG.md
  launcher.py
  lib/cogs/dogehouse.py
Labels: merge-if-wanted, size/M
