Repository DoobDev/Doob, pull requests merged in 2021-06, with the labels that each got.

#225 ➕Add amount of xp needed to next level
  CHANGELOG.md
  launcher.py
  lib/cogs/exp.py
Labels: size/XS

#230 ➕Add Fortnite Commands
  .env_example
  CHANGELOG.md
  launcher.py
  lib/cogs/exp.py
  lib/cogs/fnbr.py
Labels: size/L

#236 ➕Add member join/leave logs
  CHANGELOG.md
  launcher.py
  lib/cogs/log.py
Labels: size/M

#239 ignore this :p
  lib/cogs/mod.py
Labels: size/XS

#234 ❌Removed unused imports
  lib/cogs/bio.py
  lib/cogs/fun.py
  lib/cogs/github.py
  lib/cogs/links.py
  lib/cogs/misc.py
  lib/cogs/welcome.py
Labels: size/S

#250 ✨v2.8.9
  CHANGELOG.md
  launcher.py
  lib/cogs/fun.py
  lib/cogs/lastfm.py
  lib/cogs/mod.py
Labels: size/L

#251 ✨v2.8.9+10
  .vscode/logchannel.code-snippets
  CHANGELOG.md
  launcher.py
  lib/cogs/log.py
Labels: size/L
